### ISSUE TITLE
GFFに向けて追加したほうがいいこと

### ISSUE THREAD

**Issue by Saekikenta** [FoolFour/NeedlesRepository#33]
GFFに向けて追加した方がいいこと（足りない要素）
・ステージ選択時のSE
・クリアした時のSE
・敵の見た目を敵っぽくする

**Comment by Saekikenta** [comment]
敵の見た目を敵っぽくする（とげを付ける等攻撃的にする）

**Comment by KakeruMan** [comment]
「キャンセル」はステージ選択時のみの表記に
星々を選んでいる時(Bボタンでタイトル戻る状態)では「タイトル ヘ モドル」に変わるように

**Comment by KakeruMan** [comment]
ポーズ画面に現在のステージ数を表示

**Comment by KakeruMan** [comment]
ロード画面はワールドに対応した画像に

**Comment by KakeruMan** [comment]
ロード中にTipsとか(白猫のアレ)

**Comment by Saekikenta** [comment]
Escで強制終了

**Comment by KakeruMan** [comment]
ステージ外に飛び出せるステージは封鎖するべき(周囲を囲うなど)

**Comment by KakeruMan** [comment]
Z軸水バシャーン修正

**Comment by KakeruMan** [comment]
クリア時のカメラ移動(なくすの？)
上に移動したときに背景ブロックの切れ目とか見えないような何か

**Comment by ralsoon** [comment]
別途別のissueに書き換えたのでClose
