### ISSUE TITLE
腕の伸び縮みの問題

### ISSUE THREAD

**Issue by Jackal0024** [FoolFour/NeedlesRepository#4]
腕の伸び縮みが、スティックだとやりにくいので
ボタンで長さを変えることを提案
（ボタンはL1L2、R1R2が妥当か？）
ボタン操作が増える問題がある。
切り離しをどうするか

**Comment by tunomizu** [comment]
マックスで進むステージを作ることで半倒しを行わなくてもいいようにする
ボタンでは長さを変えない
